version: '2'
services:

  app:
    build: ./app
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - db
    volumes:
      - ../:/var/www/html
  db:
    image: mysql:5.6
    ports:
      - "3306:3306"
    volumes_from:
      - db_data
    environment:
        MYSQL_ROOT_PASSWORD: root
  db_data:
    image: busybox
    volumes:
      - ./db/data:/var/lib/mysql
